# Generated by Django 4.2.5 on 2023-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="picture",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="pictures/%Y/%m/%d/"
            ),
        ),
    ]
