# Generated by Django 4.2.5 on 2023-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_task_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="picture",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="task_images/"
            ),
        ),
    ]
