# Generated by Django 4.2.6 on 2023-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_task_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="audio",
            field=models.FileField(
                blank=True, max_length=255, null=True, upload_to="audio/"
            ),
        ),
    ]
